package splitstestwrapper

import "gitlab.com/auk-go/core/constants"

var LastTestCases = []GenericSplitWrapper{
	{
		Content:          "[ab]found....1[ab]...found...2[ab]...found3",
		SearchingContent: "[ab]",
		IsCaseSensitive:  true,
		Limits:           constants.MinusOne,
		HasPanic:         false,
		funcName:         last,
		expected: []string{
			"...found3",
			"...found...2",
			"found....1",
			"",
		},
		actual: nil,
	},
	{
		Content:          "[ab]found....1[ab]...found...2[ab]...found3[ab]",
		SearchingContent: "[ab]",
		IsCaseSensitive:  true,
		Limits:           constants.MinusOne,
		HasPanic:         false,
		funcName:         last,
		expected: []string{
			"",
			"...found3",
			"...found...2",
			"found....1",
			"",
		},
	},
	{
		Content:          "[ab]found....1[ab]...found...2[ab]...found3",
		SearchingContent: "[ab]*",
		IsCaseSensitive:  true,
		Limits:           constants.MinusOne,
		HasPanic:         false,
		funcName:         last,
		expected:         []string{"[ab]found....1[ab]...found...2[ab]...found3"},
	},
	{
		Content:          "[ab]found....1[ab]...found...2[ab]...found3[ab]",
		SearchingContent: "[aB]",
		IsCaseSensitive:  true,
		Limits:           constants.MinusOne,
		HasPanic:         false,
		funcName:         last,
		expected:         []string{"[ab]found....1[ab]...found...2[ab]...found3[ab]"},
	},
	{
		Content:          "[ab]found....1[ab]...found...2[ab]...found3[ab]",
		SearchingContent: "[ab]",
		IsCaseSensitive:  true,
		Limits:           constants.Three,
		funcName:         last,
		expected: []string{
			"",
			"...found3",
			"[ab]found....1[ab]...found...2",
		},
	},
	{
		Content:          "[ab]found....1[ab]...found...2[ab]...found3[ab]found4",
		SearchingContent: "[ab]",
		IsCaseSensitive:  true,
		Limits:           constants.Two,
		funcName:         last,
		expected: []string{
			"found4",
			"[ab]found....1[ab]...found...2[ab]...found3",
		},
	},
	{
		Content:          "found 0[ab]found....1[ab]...found...2[ab]...found3[ab]found4",
		SearchingContent: "[aB]",
		IsCaseSensitive:  false,
		Limits:           constants.MinusOne,
		HasPanic:         false,
		funcName:         last,
		expected: []string{
			"found4",
			"...found3",
			"...found...2",
			"found....1",
			"found 0",
		},
	},
	{
		Content:          "found 0[ab]found....1[ab]...found...2[ab]...found3[ab]found4",
		SearchingContent: "[aB]",
		IsCaseSensitive:  false,
		Limits:           constants.Two,
		HasPanic:         false,
		funcName:         last,
		expected: []string{
			"found4",
			"found 0[ab]found....1[ab]...found...2[ab]...found3",
		},
	},
	{
		Content:          "abcde",
		SearchingContent: "",
		IsCaseSensitive:  false,
		Limits:           constants.MinusOne,
		HasPanic:         false,
		funcName:         last,
		expected: []string{
			"e",
			"d",
			"c",
			"b",
			"a",
		},
	},
	{
		Content:          "abcde",
		SearchingContent: "",
		IsCaseSensitive:  false,
		Limits:           constants.Two,
		HasPanic:         false,
		funcName:         last,
		expected: []string{
			"e",
			"abcd",
		},
	},
}
