package splitstestwrapper

import "gitlab.com/evatix-go/core/constants"

var LastByRuneTestCases = []LastByRuneWrapper{
	{
		Content:          "/found....1/...found...2/...found3",
		SearchingContent: '/',
		IsCaseSensitive:  true,
		Limits:           constants.MinusOne,
		HasPanic:         false,
		funcName:         lastByRune,
		expected: &[]string{
			"...found3",
			"...found...2",
			"found....1",
			"",
		},
		actual: nil,
	},
	{
		Content:          "/found....1/...found...2/...found3/",
		SearchingContent: '/',
		IsCaseSensitive:  true,
		Limits:           constants.MinusOne,
		HasPanic:         false,
		funcName:         lastByRune,
		expected: &[]string{
			"",
			"...found3",
			"...found...2",
			"found....1",
			"",
		},
	},
	{
		Content:          "[ab]found....1[ab]...found...2[ab]...found3",
		SearchingContent: '/',
		IsCaseSensitive:  true,
		Limits:           constants.MinusOne,
		HasPanic:         false,
		funcName:         lastByRune,
		expected:         &[]string{"[ab]found....1[ab]...found...2[ab]...found3"},
	},
	{
		Content:          "[ab]found....1[ab]...found...2[ab]...found3[ab]",
		SearchingContent: '/',
		IsCaseSensitive:  true,
		Limits:           constants.MinusOne,
		HasPanic:         false,
		funcName:         lastByRune,
		expected:         &[]string{"[ab]found....1[ab]...found...2[ab]...found3[ab]"},
	},
	{
		Content:          "/found....1/...found...2/...found3/",
		SearchingContent: '/',
		IsCaseSensitive:  true,
		Limits:           2,
		funcName:         lastByRune,
		expected: &[]string{
			"",
			"/found....1/...found...2/...found3",
		},
	},
	{
		Content:          "/found....1/...found...2/...found3/found4",
		SearchingContent: '/',
		IsCaseSensitive:  true,
		Limits:           2,
		funcName:         lastByRune,
		expected: &[]string{
			"found4",
			"/found....1/...found...2/...found3",
		},
	},
	{
		Content:          "found 0/found....1/...found...2/...found3/found4",
		SearchingContent: '/',
		IsCaseSensitive:  true,
		Limits:           constants.MinusOne,
		HasPanic:         false,
		funcName:         lastByRune,
		expected: &[]string{
			"found4",
			"...found3",
			"...found...2",
			"found....1",
			"found 0",
		},
	},
	{
		Content:          "found 0/found....1/...found...2/...found3/found4",
		SearchingContent: '/',
		IsCaseSensitive:  true,
		Limits:           constants.Three,
		HasPanic:         false,
		funcName:         lastByRune,
		expected: &[]string{
			"found4",
			"...found3",
			"found 0/found....1/...found...2",
		},
	},
	{
		Content:          "found 0/found....1/...found...2/...found3/found4",
		SearchingContent: '/',
		IsCaseSensitive:  true,
		Limits:           constants.Two,
		HasPanic:         false,
		funcName:         lastByRune,
		expected: &[]string{
			"found4",
			"found 0/found....1/...found...2/...found3",
		},
	},
	{
		Content:          "বাংলাদেশ1/বাংলাদেশ2/বাংলাদেশ3/বাংলাদেশ4",
		SearchingContent: '/',
		IsCaseSensitive:  true,
		Limits:           constants.Three,
		HasPanic:         false,
		funcName:         lastByRune,
		expected: &[]string{
			"বাংলাদেশ4",
			"বাংলাদেশ3",
			"বাংলাদেশ1/বাংলাদেশ2",
		},
	},
}
