package testwrappers

var EndsWithTestCases = []StartsOrEndsWithTestWrapper{
	{
		WholeText:       "Alim Ul Karim",
		Search:          "Karim",
		StartsAt:        0,
		IsCaseSensitive: true,
		expected:        true,
		funcName:        isEndsWith,
	},
	{
		WholeText:       "Alim Ul Karim",
		Search:          "karim",
		StartsAt:        0,
		IsCaseSensitive: false,
		expected:        true,
		funcName:        isEndsWith,
	},
	{
		WholeText:       "Alim Ul Karim",
		Search:          "kKarim",
		StartsAt:        0,
		IsCaseSensitive: true,
		expected:        false,
		funcName:        isEndsWith,
	},
	{
		WholeText:       "Alim Ul Karim",
		Search:          "NothingNothingNothingNothing    %&^@(*)_)+",
		StartsAt:        0,
		IsCaseSensitive: true,
		expected:        false,
		funcName:        isEndsWith,
	},
	{
		WholeText:       "Alim Ul Karim",
		Search:          " ",
		StartsAt:        0,
		IsCaseSensitive: true,
		expected:        false,
		funcName:        isEndsWith,
	},
	{
		WholeText:       "Alim Ul Karim",
		Search:          "kar",
		StartsAt:        2,
		IsCaseSensitive: false,
		expected:        true,
		funcName:        isEndsWith,
	},
	{
		WholeText:       "Alim Ul Karim",
		Search:          "",
		StartsAt:        5,
		IsCaseSensitive: false,
		expected:        true,
		funcName:        isEndsWith,
	},
	{
		WholeText:       "Alim Ul Karim",
		Search:          "",
		StartsAt:        15,
		IsCaseSensitive: false,
		expected:        false,
		funcName:        isEndsWith,
	},
	{
		WholeText:       "Alim Ul Karim",
		Search:          "",
		StartsAt:        2,
		IsCaseSensitive: false,
		expected:        true,
	},
	{
		WholeText:       "",
		Search:          "",
		StartsAt:        0,
		IsCaseSensitive: false,
		expected:        true,
		funcName:        isEndsWith,
	},
	{
		WholeText:       "",
		Search:          "",
		StartsAt:        2,
		IsCaseSensitive: false,
		expected:        false,
		funcName:        isEndsWith,
	},
	{
		WholeText:       "Alim Ul Karim",
		Search:          "karim",
		StartsAt:        0,
		IsCaseSensitive: true,
		expected:        false,
		funcName:        isEndsWith,
	},
	{
		WholeText:       "Alim Ul Karim",
		Search:          "AAlim",
		StartsAt:        0,
		IsCaseSensitive: true,
		expected:        false,
		funcName:        isEndsWith,
	},
	{
		WholeText:       "Alim Ul Karim",
		Search:          "Naureen",
		StartsAt:        0,
		IsCaseSensitive: true,
		expected:        false,
		funcName:        isEndsWith,
	},
}
