package testwrappers

var StartsWithTestCases = []StartsOrEndsWithTestWrapper{
	{
		WholeText:       "Alim Ul Karim",
		Search:          "Karim",
		StartsAt:        0,
		IsCaseSensitive: true,
		expected:        false,
		funcName:        isStartsWith,
	},
	{
		WholeText:       "Alim Ul Karim",
		Search:          "alim",
		StartsAt:        0,
		IsCaseSensitive: false,
		expected:        true,
		funcName:        isStartsWith,
	},
	{
		WholeText:       "Alim Ul Karim",
		Search:          "aalim",
		StartsAt:        0,
		IsCaseSensitive: false,
		expected:        false,
		funcName:        isStartsWith,
	},
	{
		WholeText:       "Alim Ul Karim",
		Search:          "Alim",
		StartsAt:        0,
		IsCaseSensitive: true,
		expected:        true,
		funcName:        isStartsWith,
	},
	{
		WholeText:       "Alim Ul Karim",
		Search:          "Alim ul Karim",
		StartsAt:        0,
		IsCaseSensitive: false,
		expected:        true,
		funcName:        isStartsWith,
	},
	{
		WholeText:       "Alim Ul Karim",
		Search:          "Alim Ul Karim",
		StartsAt:        0,
		IsCaseSensitive: true,
		expected:        true,
		funcName:        isStartsWith,
	},
	{
		WholeText:       "Alim Ul Karim",
		Search:          "Alim ",
		StartsAt:        0,
		IsCaseSensitive: true,
		expected:        true,
		funcName:        isStartsWith,
	},
	{
		WholeText:       "Alim Ul Karim",
		Search:          "NothingNothingNothingNothing    %&^@(*)_)+",
		StartsAt:        0,
		IsCaseSensitive: true,
		expected:        false,
		funcName:        isStartsWith,
	},
	{
		WholeText:       "Alim Ul Karim",
		Search:          " ",
		StartsAt:        0,
		IsCaseSensitive: true,
		expected:        false,
		funcName:        isStartsWith,
	},
	{
		WholeText:       "Alim Ul Karim",
		Search:          "Im uL",
		StartsAt:        2,
		IsCaseSensitive: false,
		expected:        true,
		funcName:        isStartsWith,
	},
	{
		WholeText:       "Alim Ul Karim",
		Search:          "",
		StartsAt:        2,
		IsCaseSensitive: false,
		expected:        true,
		funcName:        isStartsWith,
	},
	{
		WholeText:       "Alim Ul Karim",
		Search:          "",
		StartsAt:        15,
		IsCaseSensitive: false,
		expected:        false,
		funcName:        isStartsWith,
	},
	{
		WholeText:       "",
		Search:          "",
		StartsAt:        0,
		IsCaseSensitive: false,
		expected:        true,
		funcName:        isStartsWith,
	},
	{
		WholeText:       "     ",
		Search:          "",
		StartsAt:        2,
		IsCaseSensitive: false,
		expected:        true,
		funcName:        isStartsWith,
	},
	{
		WholeText:       "Naureen Afrose review the code",
		Search:          "did Alim reviewed?",
		StartsAt:        0,
		IsCaseSensitive: true,
		expected:        false,
		funcName:        isStartsWith,
	},
}
