package indextestwrappers

import "gitlab.com/evatix-go/core/constants"

var OfAllPtrCasesPtr = []GenericIndexOfWrapper{
	{
		Content:             "[ab]found me[ab][ab]notfound",
		SearchingContent:    "[ab]",
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     true,
		Limits:              constants.MinusOne,
		funcName:            ofAllPtr,
		expected:            &[]int{0, 12, 16},
	},
	{
		Content:             "[ab]found me[ab][ab]notfound",
		SearchingContent:    "[ab]*",
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     true,
		Limits:              constants.MinusOne,
		funcName:            ofAllPtr,
		expected:            nil,
	},
	{
		Content:             "[ab]found me[ab][ab]notfound",
		SearchingContent:    "[aB]",
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     true,
		Limits:              constants.MinusOne,
		funcName:            ofAllPtr,
		expected:            nil,
	},
	{
		Content:             "[ab]found me[ab][ab]notfound",
		SearchingContent:    "[aB]",
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     false,
		Limits:              constants.MinusOne,
		funcName:            ofAllPtr,
		expected:            &[]int{0, 12, 16},
	},
	{
		Content:             "[ab]found me[ab][ab]notfound",
		SearchingContent:    "[aB]",
		InitializedPosition: 2,
		IsCaseSensitive:     false,
		Limits:              constants.MinusOne,
		funcName:            ofAllPtr,
		expected:            &[]int{12, 16},
	},
	{
		Content:             "[ab][ab]found me[ab][ab]notfound[ab]",
		SearchingContent:    "[aB]",
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     false,
		Limits:              constants.MinusOne,
		funcName:            ofAllPtr,
		expected:            &[]int{0, 4, 16, 20, 32},
	},
	{
		Content:             "[ab][ab]found me[ab][ab]notfound[ab]",
		SearchingContent:    "[aB]",
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     false,
		Limits:              3,
		funcName:            ofAllPtr,
		expected:            &[]int{0, 4, 16},
	},
	{
		Content:             "[ab][ab]found me[ab][ab]notfound[Ab]",
		SearchingContent:    "[aB]",
		InitializedPosition: 2,
		IsCaseSensitive:     false,
		Limits:              constants.MinusOne,
		funcName:            ofAllPtr,
		expected:            &[]int{4, 16, 20, 32},
	},
	{
		Content:             "[ab][ab]found me[Ab][ab]notfound[ab]",
		SearchingContent:    "[aB]",
		InitializedPosition: 2,
		IsCaseSensitive:     false,
		Limits:              constants.MinusOne,
		funcName:            ofAllPtr,
		expected:            &[]int{4, 16, 20, 32},
	},
	{
		Content:             "[ab][ab]found me[Ab][ab]notfound[ab]",
		SearchingContent:    "[aB]",
		InitializedPosition: 2,
		IsCaseSensitive:     true,
		Limits:              constants.MinusOne,
		funcName:            ofAllPtr,
		expected:            nil,
	},
	{
		Content:             "[ab][ab]found me[Ab][ab]notfound[ab]",
		SearchingContent:    "[ab][ab]found me[Ab][ab]notfound[ab][aB]",
		InitializedPosition: 2,
		IsCaseSensitive:     true,
		Limits:              constants.MinusOne,
		funcName:            ofAllPtr,
		expected:            nil,
	},
	{
		Content:             "[ab][ab]found me[Ab][ab]notfound[ab]",
		SearchingContent:    "[ab][ab]found me[Ab][AB]notfound[ab]",
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     false,
		Limits:              constants.MinusOne,
		funcName:            ofAllPtr,
		expected:            &[]int{0},
	},
	{
		Content:             "[ab][ab]found me[Ab][ab]notfound[ab]",
		SearchingContent:    "[ab][ab]found me[Ab][AB]notfound[ab]",
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     false,
		Limits:              constants.MinusOne,
		funcName:            ofAllPtr,
		expected:            &[]int{0},
	},
	{
		Content:             "abcdef",
		SearchingContent:    "",
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     false,
		Limits:              constants.MinusOne,
		funcName:            ofAllPtr,
		expected:            &[]int{0, 1, 2, 3, 4, 5},
	},
	{
		Content:             "abcdef",
		SearchingContent:    "",
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     false,
		Limits:              4,
		funcName:            ofAllPtr,
		expected:            &[]int{0, 1, 2, 3},
	},
	{
		Content:             "abcdef",
		SearchingContent:    "",
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     true,
		Limits:              constants.MinusOne,
		funcName:            ofAllPtr,
		expected:            &[]int{0, 1, 2, 3, 4, 5},
	},
	{
		Content:             constants.EmptyString,
		SearchingContent:    constants.EmptyString,
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     true,
		Limits:              constants.MinusOne,
		funcName:            ofAllPtr,
		expected:            &[]int{0},
	},
	{
		Content:             constants.EmptyString,
		SearchingContent:    constants.EmptyString,
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     true,
		Limits:              constants.Zero,
		funcName:            ofAllPtr,
		expected:            nil,
	},
	{
		Content:             "ab",
		SearchingContent:    "a",
		InitializedPosition: 1,
		IsCaseSensitive:     true,
		Limits:              constants.MinusOne,
		funcName:            ofAllPtr,
		expected:            nil,
	},
}
