package indextestwrappers

var OfAllCases = []GenericIndexOfTestWrapper{
	{
		Content:             "[ab]found me[ab][ab]notfound",
		SearchingContent:    "[ab]",
		InitializedPosition: 0,
		IsCaseSensitive:     true,
		Limits:              -1,
		funcName:            ofAll,
		expected:            &[]int{0, 12, 16},
	},
	{
		Content:             "[ab]found me[ab][ab]notfound",
		SearchingContent:    "[ab]*",
		InitializedPosition: 0,
		IsCaseSensitive:     true,
		Limits:              -1,
		funcName:            ofAll,
		expected:            nil,
	},
	{
		Content:             "[ab]found me[ab][ab]notfound",
		SearchingContent:    "[aB]",
		InitializedPosition: 0,
		IsCaseSensitive:     true,
		Limits:              -1,
		funcName:            ofAll,
		expected:            nil,
	},
	{
		Content:             "[ab]found me[ab][ab]notfound",
		SearchingContent:    "[aB]",
		InitializedPosition: 0,
		IsCaseSensitive:     false,
		Limits:              -1,
		funcName:            ofAll,
		expected:            &[]int{0, 12, 16},
	},
	{
		Content:             "[ab]found me[ab][ab]notfound",
		SearchingContent:    "[aB]",
		InitializedPosition: 2,
		IsCaseSensitive:     false,
		Limits:              -1,
		funcName:            ofAll,
		expected:            &[]int{12, 16},
	},
	{
		Content:             "[ab][ab]found me[ab][ab]notfound[ab]",
		SearchingContent:    "[aB]",
		InitializedPosition: 0,
		IsCaseSensitive:     false,
		Limits:              -1,
		funcName:            ofAll,
		expected:            &[]int{0, 4, 16, 20, 32},
	},
	{
		Content:             "[ab][ab]found me[ab][ab]notfound[ab]",
		SearchingContent:    "[aB]",
		InitializedPosition: 0,
		IsCaseSensitive:     false,
		Limits:              3,
		funcName:            ofAll,
		expected:            &[]int{0, 4, 16},
	},
	{
		Content:             "[ab][ab]found me[ab][ab]notfound[Ab]",
		SearchingContent:    "[aB]",
		InitializedPosition: 2,
		IsCaseSensitive:     false,
		Limits:              -1,
		funcName:            ofAll,
		expected:            &[]int{4, 16, 20, 32},
	},
	{
		Content:             "[ab][ab]found me[Ab][ab]notfound[ab]",
		SearchingContent:    "[aB]",
		InitializedPosition: 2,
		IsCaseSensitive:     false,
		Limits:              -1,
		funcName:            ofAll,
		expected:            &[]int{4, 16, 20, 32},
	},
}
