package indextestwrappers

import "gitlab.com/evatix-go/core/constants"

var OfLastAllPtrCasesPtr = &[]GenericIndexOf{
	{
		Content:             "[ab]found me[ab][ab]notfound",
		SearchingContent:    "[ab]",
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     true,
		Limits:              constants.MinusOne,
		funcName:            ofLastAllPtr,
		expected:            &[]int{16, 12, 0},
	},
	{
		Content:             "[ab]found me[ab][ab]notfound",
		SearchingContent:    "[ab]*",
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     true,
		Limits:              constants.MinusOne,
		funcName:            ofLastAllPtr,
		expected:            nil,
	},
	{
		Content:             "[ab]found me[ab][ab]notfound",
		SearchingContent:    "[aB]",
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     true,
		Limits:              constants.MinusOne,
		funcName:            ofLastAllPtr,
		expected:            nil,
	},
	{
		Content:             "[ab]found me[ab][ab]notfound",
		SearchingContent:    "[aB]",
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     false,
		Limits:              constants.MinusOne,
		funcName:            ofLastAllPtr,
		expected:            &[]int{16, 12, 0},
	},
	{
		Content:             "[ab]found me[ab][ab]notfound",
		SearchingContent:    "[aB]",
		InitializedPosition: 2,
		IsCaseSensitive:     false,
		Limits:              2,
		funcName:            ofLastAllPtr,
		expected:            &[]int{16, 12},
	},
	{
		Content:             "[ab]found me[ab][ab]notfound",
		SearchingContent:    "[aB]",
		InitializedPosition: 2,
		IsCaseSensitive:     false,
		Limits:              constants.MinusOne,
		funcName:            ofLastAllPtr,
		expected:            &[]int{16, 12, 0},
	},
	{
		Content:             "[ab][ab]found me[ab][ab]notfound[ab]",
		SearchingContent:    "[aB]",
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     false,
		Limits:              constants.MinusOne,
		funcName:            ofLastAllPtr,
		expected:            &[]int{32, 20, 16, 4, 0},
	},
	{
		Content:             "[ab][ab]found me[ab][ab]notfound[ab]",
		SearchingContent:    "[aB]",
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     false,
		Limits:              3,
		funcName:            ofLastAllPtr,
		expected:            &[]int{32, 20, 16},
	},
	{
		Content:             "[ab][ab]found me[ab][ab]notfound[Ab]",
		SearchingContent:    "[aB]",
		InitializedPosition: 2,
		IsCaseSensitive:     false,
		Limits:              constants.MinusOne,
		funcName:            ofLastAllPtr,
		expected:            &[]int{20, 16, 4, 0},
	},
	{
		Content:             "[ab][ab]found me[Ab][ab]notfound[ab]",
		SearchingContent:    "[aB]",
		InitializedPosition: 2,
		IsCaseSensitive:     false,
		Limits:              constants.MinusOne,
		funcName:            ofLastAllPtr,
		expected:            &[]int{20, 16, 4, 0},
	},
	{
		Content:             "[ab][ab]found me[Ab][ab]notfound[ab]",
		SearchingContent:    "[aB]",
		InitializedPosition: 2,
		IsCaseSensitive:     true,
		Limits:              constants.MinusOne,
		funcName:            ofLastAllPtr,
		expected:            nil,
	},
	{
		Content:             "[ab][ab]found me[Ab][ab]notfound[ab]",
		SearchingContent:    "[ab][ab]found me[Ab][ab]notfound[ab][aB]",
		InitializedPosition: 2,
		IsCaseSensitive:     true,
		Limits:              constants.MinusOne,
		funcName:            ofLastAllPtr,
		expected:            nil,
	},
	{
		Content:             "[ab][ab]found me[Ab][ab]notfound[ab]",
		SearchingContent:    "[ab][ab]found me[Ab][AB]notfound[ab]",
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     false,
		Limits:              constants.MinusOne,
		funcName:            ofLastAllPtr,
		expected:            &[]int{0},
	},
	{
		Content:             "[ab][ab]found me[Ab][ab]notfound[ab]",
		SearchingContent:    "[ab][ab]found me[Ab][AB]notfound[ab]",
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     false,
		Limits:              constants.MinusOne,
		funcName:            ofLastAllPtr,
		expected:            &[]int{0},
	},
	{
		Content:             "abcdef",
		SearchingContent:    "",
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     false,
		Limits:              constants.MinusOne,
		funcName:            ofLastAllPtr,
		expected:            &[]int{5, 4, 3, 2, 1, 0},
	},
	{
		Content:             "abcdef",
		SearchingContent:    "",
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     false,
		Limits:              4,
		funcName:            ofLastAllPtr,
		expected:            &[]int{3, 2, 1, 0},
	},
	{
		Content:             "abcdef",
		SearchingContent:    "",
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     true,
		Limits:              constants.MinusOne,
		funcName:            ofLastAllPtr,
		expected:            &[]int{5, 4, 3, 2, 1, 0},
	},
	{
		Content:             constants.EmptyString,
		SearchingContent:    constants.EmptyString,
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     true,
		Limits:              constants.MinusOne,
		funcName:            ofLastAllPtr,
		expected:            &[]int{0},
	},
	{
		Content:             constants.EmptyString,
		SearchingContent:    constants.EmptyString,
		InitializedPosition: constants.Zero,
		IsCaseSensitive:     true,
		Limits:              constants.Zero,
		funcName:            ofLastAllPtr,
		expected:            nil,
	},
	{
		Content:             "ab",
		SearchingContent:    "a",
		InitializedPosition: 1,
		IsCaseSensitive:     true,
		Limits:              constants.MinusOne,
		funcName:            ofLastAllPtr,
		expected:            &[]int{0},
	},
}
